App\Entity\Company:
  collectionOperations:
    get:
      normalization_context:
        groups:
          - "company:read"
  itemOperations:
    get:
      normalization_context:
        groups:
          - "company:read"