App\Entity\Project:
  collectionOperations:
    get:
      normalization_context:
        groups:
          - "project:read"
  itemOperations:
    get:
      normalization_context:
        groups:
          - "project:read"